name: Update GOLF JSON Files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the branch
  push:
    branches: [ golf ]
  pull_request:
    branches: [ golf ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Copy JSON File
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.GCP_INSTANCE_USERNAME }}
          server: ${{ secrets.GCP_INSTANCE_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './*.json'
          remote_path: ${{ secrets.GCP_INSTANCE_PATH_GOLF }}
          args: '-o ConnectTimeout=5'
